import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ClientProviders from '@/Components/Provider/ClientProvider';
import Wrapper from '@/Components/Wrapper';
import AsyncLoadingProvider from '@/Components/Common/AsyncLoading/AsyncLoading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ClientProviders>
					<div className="bg-gray-500 h-screen">
						<Wrapper>
							<AsyncLoadingProvider />
							{children}
						</Wrapper>
					</div>
				</ClientProviders>
			</body>
		</html>
	);
}
